spring.application.name=tasks

spring.datasource.url=jdbc:postgresql://localhost:5432/practice
spring.datasource.username=postgres_tasks
spring.datasource.password=10293
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080

# JPA and Hibernate settings (optional, but recommended)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=fabrica
spring.datasource.hikari.schema=fabrica
