spring.application.name=tasks

spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:5432/postgres?sslmode=require
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081

# JPA and Hibernate settings (optional, but recommended)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=fabrica
spring.datasource.hikari.schema=fabrica


# User validation service configuration
user.validation.service.url=${USER_VALIDATION_SERVICE_URL:http://localhost:8080}