spring.application.name=tasks

spring.datasource.url=${DATABASE_URL:jdbc:postgresql}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=task_management
server.port=${PORT:8081}

# JPA and Hibernate settings (optional, but recommended)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# User validation service configuration
user.validation.service.url=${USER_VALIDATION_SERVICE_URL}
jwt.secret=${JWT_SECRET}
jwt.expiration.time=86400000

# Azure Storage Queue configuration
spring.storage.queue.connection-string=${AZURE_STORAGE_CONNECTION_STRING}
spring.storage.queue.name=authentication
auth.service.url=${AUTH_SERVICE_URL}

# Azure Service Bus para logs de auditoria
audit.log.servicebus.connection-string=${AUDIT_LOG_CONNECTION_STRING}
audit.log.servicebus.queue-name=${AUDIT_LOG_QUEUE_NAME}
