spring.application.name=authentication

spring.config.import=optional:file:.env[.properties]

# User queue configuration
azure.storage.users.connection-string=${CONNECTION_STRING}
azure.storage.users.queue-name=${QUEUE_NAME}

# task users queue
azure.storage.users-task.connection-string=${TASK_USERS_CONNECTION_STRING}
azure.storage.users-task.queue-name=${TASK_USERS_QUEUE_NAME}

# DataSource Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# This only CREATES tables that don't exist, never drops
spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=src/main/resources/schema.sql
spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata

# THIS IS THE KEY — only generate the script, never execute it
spring.jpa.hibernate.ddl-auto=none

# token expiration time
jwt.access.expiration=3600000
jwt.refresh.expiration=604800000
jwt.secret=${JWT_SECRET_KEY}
