### Create a new task 
POST http://localhost:8081/task
Content-Type: application/json

{
  "name": "lipiar los trastos",
  "description": "limpiar con agua y jabon los platos",
  "priorityName": "LOW",
  "statusName": "PENDING",
  "deadline": "2026-06-30T23:59:00",
  "guestId": "126949ed-8168-4078-a046-1ac4f3cea220",
  "homeId": "3e0562d9-f3f9-4376-a4d0-5446991f2054"
}

### Get all tasks 
GET http://localhost:8081/task