apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  db-password: contraseñasegura1234
  jwt-secret: miclavesecreta_conmuchosnumeros123415ycaracteresraros()&*&%^%&^final
  email-sender: brayanjaraba2006
  email-password: gsqtbqaquujhflus
  azure-connection-string: DefaultEndpointsProtocol=https;AccountName=fabricaescula;AccountKey=L9JwmDbiBipaKfIAmmR73tFII+wOvRuMqXTdsGsXQwmedbpQJJ1ivpWTHOmWlpzGamMYlVlKKxvz+AStOWGD+A==;EndpointSuffix=core.windows.net
  membership-service-queue-name: authentication
  tasks-service-queue-name: users-task
