services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: fabrica
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d fabrica"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: familiar-tasks-authentication
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/fabrica
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      AZURE_CONNECTION_STRING: ${AZURE_CONNECTION_STRING}
      MEMBERSHIP_SERVICE_QUEUE_NAME: ${MEMBERSHIP_SERVICE_QUEUE_NAME}
      TASKS_SERVICE_QUEUE_NAME: ${TASKS_SERVICE_QUEUE_NAME}
      EMAIL_SENDER: ${EMAIL_SENDER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    ports:
      - "8080:8080"

volumes:
  postgres_data:
